@echo off
echo Fixing Vite module error...
echo Deleting corrupted node_modules...
rmdir /s /q node_modules
echo Deleting package-lock.json...
del package-lock.json
echo Reinstalling dependencies...
npm install
echo Fixed! Starting dev server...
npm run dev