
[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["supertokens-node"]
  included_files = ["node_modules/supertokens-node/**"]
  
[[redirects]]
  from = "/api/auth/*"
  to = "/.netlify/functions/supertokens"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
